#!/usr/bin/env python3
"""Regenerate AGENTS.md from the current TalkBack repo layout.

Run from repository root:
  python3 scripts/generate_agents_md.py
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


def _list_names(root: Path, pattern: str) -> list[str]:
    return sorted(p.name for p in root.glob(pattern) if p.is_file())


def _tests_list(root: Path) -> list[str]:
    d = root / "tests"
    if not d.is_di

def _mcp_check_commands(root: Path) -> list[str]:
    """Concrete python3 … lines for files that exist (repo root)."""
    candidates = [
        ("test_mcp_connection.py", None),
        ("test_mcp_roast.py", "'python3 broken_code.py'"),
        ("test_roast.py", "2"),
    ]
    lines: list[str] = []
    for script, arg in candidates:
        if (root / script).is_file():
            if arg is None:
                lines.append(f"  - `python3 {script}`")
            elif script == "test_roast.py":
                lines.append(f"  - `python3 {script} {arg}`  _(example severity level)_")
            else:
                lines.append(f"  - `python3 {script} {arg}`")
    if not lines:
        lines.append("  - _(no MCP test scripts found in repo root — add `test_mcp_connection.py` etc.)_")
    return lines


def build_markdown(root: Path) -> str:
    swift_files = _list_names(root, "*.swift")
    py_root = _list_names(root, "*.py")
    shell_scripts = _list_names(root, "*.sh")
    test_modules = _tests_list(root)

    main_swift = swift_files[0] if swift_files else "ConversationalTalkBack.swift"
    build_cmd = (
        f"swiftc -o ConversationalTalkBack {main_swift} "
        "-framework Cocoa -framework Foundation -framework AVFoundation "
        "-target arm64-apple-macosx13.0"
    )

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    swift_bullets = "\n".join(f"- `{n}`" for n in swift_files) or "- _(none — add `*.swift` at repo root)_"
    py_bullets = "\n".join(f"- `{n}`" for n in py_root) or "- _(none)_"
    shell_bullets = (
        "\n".join(f"- `{n}`" for n in shell_scripts)
        or "- _(none)_"
    )
    
        tests_bullets = "- _(no `tests/test_*.py` found)_"
    mcp_lines = "\mcp_check_commands(root))

    return f"""# Agent Guide

<!-- Generated by scripts/generate_agents_md.py — edit the script or static sections inside it, not this file by hand. -->

_Last regenerated: {generated}_

This file gives quick context and working rules for AI coding agents in this repository.

## Project Overview

- **App:** TalkBack (macOS floating AI companion with voice + vision features).
- **Primary runtime file:** `{main_swift}` (see inventory below).

### Repository inventory (auto-discovered)

**Swift (repo root)**

{swift_bullets}

**Python (repo root)**

{py_bullets}

**Shell (repo root)**

{shell_bullets}

**Python tests (`tests/`)**

{tests_bullets}

## Common Workflows

- **Build app**
  - `{build_cmd}`
- **Run app**
  - `./ConversationalTalkBack`
- **MCP integration checks** _(scripts present on disk)_
{mcp_lines}

## Editing Guidelines

- Keep changes focused and minimal.
- Do not commit secrets or API keys.
- Prefer updating docs when behavior or setup changes.
- Avoid destructive git commands unless explicitly requested.

## README.md Guidelines

- Always include a `Table of Contents` section in `README.md` for quick navigation.
- Update the table of contents whenever headings are added, removed, or renamed.
- Update `README.md` whenever setup, commands, features, or user-visible behavior changes.
- Keep `Quick Start`, prerequisites, and troubleshooting steps aligned with current code.
- Ensure all command snippets are copy-paste ready and valid from repo root unless noted.
- When adding new scripts or integrations, add at least one concrete usage example.
- Use concise, actionable language and avoid vague instructions.
- If no README changes are needed for a code change, explicitly state why in your task notes.
- After adding or renaming root-level Swift/Python/shell files, run `python3 scripts/generate_agents_md.py` to refresh this guide.

## Validation Checklist

- Confirm Swift and Python scripts still run after edits.
- Verify docs commands remain accurate.
- Check for obvious lint/type/runtime errors in edited files.
"""


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    out = root / "AGENTS.md"
    out.write_text(build_markdown(root), encoding="utf-8")
    print(f"Wrote {out.relative_to(root)}")


if __name__ == "__main__":
    main()
